# This is a configuration file for cargo-deny
# See https://embarkstudios.github.io/cargo-deny/

[licenses]
# Explicitly allow these license identifiers
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC",
    "Zlib",
    "0BSD",
    "BSL-1.0",
    "Unicode-DFS-2016",
]

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

# Allow unlicensed crates
[[licenses.clarify]]
version = 1
expression = "MIT OR Apache-2.0"
license-files = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

[sources]
# Allow crates from crates.io and GitHub
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com"]
